url: https://ismwestcoast.github.io

# Site settings
title: ISM Westcoast
email: info@ismwestcoast.com.au.com
description: "Music Education for Children of All Ages"


# Team names, titles and social links
people:
- name: Lynette Telfer
  pic: 1
  position: Director
  branch: all

- name: Stephanie Wigunadharma
  pic: 2
  position: Music Teacher
  branch: wembley

- name: Ricky Lin
  pic: 3
  position: Music Teacher
  branch: wembley

- name: Georgia Harris
  pic: 3
  position: Music Teacher
  branch: wembley

- name: Hannah
  pic: 3
  position: Private Piano Teacher
  branch: wembley

- name: Emily
  pic: 3
  position: Music Teacher
  branch: carine

- name: Holly
  pic: 3
  position: Music Teacher
  branch: carine

# Build settings
markdown: kramdown
permalink: pretty
